// FILE: app/_components/BuildToolWidget.tsx
import React from 'react';
import Link from 'next/link';
import { WrenchIcon, LightBulbIcon } from '@heroicons/react/24/solid';

interface BuildToolWidgetProps {
  suggestedDirectives: string[];
  modelNameUsed?: string | null;
}

export default function BuildToolWidget({
  suggestedDirectives,
  modelNameUsed,
}: BuildToolWidgetProps) {
  return (
    <div className="p-4 border border-[rgb(var(--color-border-base))] rounded-lg bg-[rgb(var(--color-bg-component))] shadow-sm">
      {/* Main Build Section */}
      <div>
        <h2 className="text-xl font-semibold mb-3 text-[rgb(var(--color-text-base))]">
          Build a New Tool
        </h2>
        <p className="text-[rgb(var(--color-text-muted))] mb-4">
          Have an idea for another useful client-side utility? Build it with AI
          assistance!
        </p>
        <Link
          href="/build/tool/"
          className="inline-flex items-center px-5 py-2 bg-[rgb(var(--color-button-primary-bg))] text-[rgb(var(--color-button-primary-text))] font-medium text-sm rounded-md shadow-sm hover:bg-[rgb(var(--color-button-primary-hover-bg))] focus:outline-none transition-colors"
        >
          <WrenchIcon className="h-5 w-5 mr-2" /> Build a Tool
        </Link>
        <p className="text-[rgb(var(--color-text-muted))] mt-4">
          Use AI (Gemini) to validate the directive and attempt to generate a
          proof-of-concept tool. Successful generations will result in a pull
          request for review and potential inclusion in the site.
        </p>
      </div>

      {/* AI Suggestions Section (Conditional) */}
      {suggestedDirectives && suggestedDirectives.length > 0 && (
        <div className="pt-4 border-t border-[rgb(var(--color-border-soft))]">
          <h3 className="text-md font-semibold text-[rgb(var(--color-text-base))] mb-3 flex items-center">
            <LightBulbIcon className="h-5 w-5 mr-2 text-yellow-500" />
            Need Inspiration? AI Suggestions:
          </h3>
          {/* Changed ul to be a flex row that wraps */}
          <ul className="flex flex-row flex-wrap gap-x-3 gap-y-2">
            {suggestedDirectives.map((directive) => (
              <li key={directive}>
                <Link
                  href={`/build/tool?directive=${encodeURIComponent(directive)}`}
                  className="inline-block transition-colors text-[rgb(var(--color-text-link))] hover:text-[rgb(var(--color-text-link-hover))]"
                  title={`Start building '${directive}'`}
                >
                  <code className="bg-[rgb(var(--color-bg-neutral-subtle))] text-[rgb(var(--color-text-code))] hover:bg-[rgb(var(--color-bg-neutral))] px-2 py-1 rounded text-sm font-mono">
                    {directive}
                  </code>
                </Link>
              </li>
            ))}
          </ul>
          {modelNameUsed && (
            <p className="text-xs text-[rgb(var(--color-text-muted))] mt-4 pt-3 border-t border-[rgb(var(--color-border-soft))]">
              Suggestions generated by AI using model:{' '}
              {modelNameUsed.replace('models/', '')}
            </p>
          )}
        </div>
      )}
    </div>
  );
}
