# .github/workflows/ai-lint-fixer.yml
name: AI Lint Fixer

on:
  workflow_run:
    workflows: ['Validate Generated Tool PR']
    types:
      - completed

jobs:
  attempt_fix:
    name: Attempt AI Lint Fix
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      actions: read 
    # No need to explicitly pass GITHUB_TOKEN to env for this specific change, 
    # as we'll pass it directly to the action.

    steps:
      - name: Get Triggering Workflow Run Info
        id: get_trigger_info # Simplified this step's purpose for now
        run: |
          echo "Triggering Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Expected Artifact Name: lint-failure-data-${{ github.event.workflow_run.head_sha }}"
          echo "PR Head Branch for push: ${{ github.event.workflow_run.head_branch }}"
          echo "Commit SHA for checkout: ${{ github.event.workflow_run.head_sha }}"

      # Removed the github-script step that lists artifacts for now to simplify
      # We'll rely on download-artifact with the token

      - name: Download Lint Failure Artifact
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: lint-failure-data-${{ github.event.workflow_run.head_sha }}
          path: ${{ runner.temp }}/lint-data
          github-token: ${{ secrets.GITHUB_TOKEN }} # Explicitly provide the token
          # We don't need 'repository' or 'run-id' if it's from the triggering workflow_run in the same repo
          # The action should infer this if 'run-id' is not provided for the current repo.
          # However, to be very explicit for cross-run access:
          run-id: ${{ github.event.workflow_run.id }} 
        continue-on-error: true

      - name: Check if Artifact Exists and Contains Data
        id: check_artifact
        # This condition now directly checks the outcome of the download_artifact step
        if: steps.download_artifact.outcome == 'success' 
        run: |
          LINT_ERRORS_FILE="${{ runner.temp }}/lint-data/lint_errors.txt"
          FILES_TO_CHECK_FILE="${{ runner.temp }}/lint-data/files_to_check.txt"

          echo "Download artifact step outcome: ${{ steps.download_artifact.outcome }}"
          echo "Checking for file: $LINT_ERRORS_FILE"
          ls -la "${{ runner.temp }}/lint-data/" # List contents for debugging

          if [ -f "$LINT_ERRORS_FILE" ] && [ -s "$LINT_ERRORS_FILE" ] && \
             [ -f "$FILES_TO_CHECK_FILE" ] && [ -s "$FILES_TO_CHECK_FILE" ]; then
            echo "Lint failure artifacts found and are not empty."
            echo "artifact_valid=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Lint failure artifact files (lint_errors.txt or files_to_check.txt) not found or empty after download attempt."
            echo "artifact_valid=false" >> $GITHUB_OUTPUT
            # Consider failing the job here if files are critical and download claimed success but files are missing
            # exit 1 
          fi
          
      - name: Checkout PR Code
        if: steps.check_artifact.outputs.artifact_valid == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} 
          fetch-depth: 0 

      # ... (Rest of the steps: Prepare Data, Call API, Apply Fixes remain the same)
      # Ensure their `if` conditions correctly key off `steps.check_artifact.outputs.artifact_valid == 'true'`

      - name: Prepare Data for AI Lint Fix API
        id: prepare_fix_data
        if: steps.check_artifact.outputs.artifact_valid == 'true'
        # ... (script as before) ...
        run: |
          LINT_ERRORS_FILE="${{ runner.temp }}/lint-data/lint_errors.txt"
          FILES_TO_CHECK_FILE="${{ runner.temp }}/lint-data/files_to_check.txt"
          PR_FILES_JSON_PATH="${{ runner.temp }}/pr_files_for_lint_fix.json"

          echo '[' > $PR_FILES_JSON_PATH
          FIRST_FILE=true
          while IFS= read -r filepath; do
            if [ -f "$filepath" ]; then
              if [ "$FIRST_FILE" = "false" ]; then
                echo ',' >> $PR_FILES_JSON_PATH
              fi
              FILE_CONTENT_RAW=$(cat "$filepath")
              jq -n --arg path "$filepath" --arg content "$FILE_CONTENT_RAW" \
                '{path: $path, currentContent: $content}' >> $PR_FILES_JSON_PATH
              FIRST_FILE=false
            else
              echo "::warning::File path from artifact not found in checkout: $filepath"
            fi
          done < "$FILES_TO_CHECK_FILE"
          echo ']' >> $PR_FILES_JSON_PATH
          
          jq -s 'if type == "array" and length > 0 and (.[0] | type) == "array" then .[0] else . end' $PR_FILES_JSON_PATH > temp_final.json && mv temp_final.json $PR_FILES_JSON_PATH
          echo "Prepared files JSON for API: $PR_FILES_JSON_PATH"

      - name: Call AI Lint Fix API
        id: call_fix_api
        if: steps.prepare_fix_data.outcome == 'success' && steps.check_artifact.outputs.artifact_valid == 'true'
        # ... (script as before) ...
        env:
          LINT_FIX_API_ENDPOINT: ${{ secrets.BACKEND_APP_URL }}/api/fix-linting-errors
        run: |
          LINT_ERRORS_CONTENT=$(cat "${{ runner.temp }}/lint-data/lint_errors.txt")
          LINT_ERRORS_JSON_ESCAPED=$(echo "$LINT_ERRORS_CONTENT" | jq -R -s '.')
          FILES_TO_FIX_JSON_CONTENT=$(cat "${{ runner.temp }}/pr_files_for_lint_fix.json")

          if ! echo "$FILES_TO_FIX_JSON_CONTENT" | jq -e 'type == "array" and length > 0' > /dev/null; then
            echo "::warning::No valid files to fix after preparation. Skipping API call."
            echo "api_call_skipped=true" >> $GITHUB_OUTPUT
            exit 0 
          fi

          API_PAYLOAD=$(jq -n \
            --argjson filesToFix "$FILES_TO_FIX_JSON_CONTENT" \
            --argjson lintErrors "$LINT_ERRORS_JSON_ESCAPED" \
            --arg modelName "models/gemini-1.5-pro-latest" \
            '{filesToFix: $filesToFix, lintErrors: $lintErrors, modelName: $modelName}')

          echo "Calling AI Lint Fix API..."
          HTTP_RESPONSE_CODE=$(curl -s -w "%{http_code}" -X POST "$LINT_FIX_API_ENDPOINT" \
            -H "Content-Type: application/json" \
            -d "$API_PAYLOAD" \
            -o "${{ runner.temp }}/fix_response.json")

          if [ "$HTTP_RESPONSE_CODE" -ne 200 ]; then
            echo "::error::AI Lint Fix API call failed with HTTP status $HTTP_RESPONSE_CODE."
            cat "${{ runner.temp }}/fix_response.json" 
            exit 1
          fi

          if ! jq -e . "${{ runner.temp }}/fix_response.json" > /dev/null 2>&1; then
            echo "::error::AI Lint Fix API response is not valid JSON."
            cat "${{ runner.temp }}/fix_response.json"
            exit 1
          fi
          
          FIX_API_SUCCESS=$(jq -r .success "${{ runner.temp }}/fix_response.json")
          echo "Fix API Reported Success: $FIX_API_SUCCESS"
          echo "api_response_success=$FIX_API_SUCCESS" >> $GITHUB_OUTPUT
          echo "api_response_path=${{ runner.temp }}/fix_response.json" >> $GITHUB_OUTPUT
          echo "api_call_skipped=false" >> $GITHUB_OUTPUT

      - name: Apply and Commit Fixes
        if: steps.call_fix_api.outputs.api_call_skipped != 'true' && steps.call_fix_api.outputs.api_response_success == 'true' && steps.check_artifact.outputs.artifact_valid == 'true'
        # ... (script as before, ensure GITHUB_TOKEN is available for push if needed by app, though direct push uses runner's implicit token)
        run: |
          FIX_RESPONSE_FILE="${{ steps.call_fix_api.outputs.api_response_path }}"
          echo "AI Lint Fix API call reported success. Applying fixes from $FIX_RESPONSE_FILE..."
          
          LAST_COMMIT_MSG_ON_BRANCH=$(git log -1 --pretty=%B)

          if [[ "$LAST_COMMIT_MSG_ON_BRANCH" == "chore: AI-assisted lint fixes" ]]; then
            echo "::warning::The latest commit on the branch is already an AI lint fix. Skipping new commit to prevent loop."
            exit 0 
          fi

          CHANGES_APPLIED=false
          jq -r '.fixedFiles | to_entries[] | select(.value != null) | "\(.key)\u0000\(.value)"' "$FIX_RESPONSE_FILE" | \
          while IFS=$'\0' read -r filepath fixedcontent; do
            if [ -z "$filepath" ]; then continue; fi
            if [ ! -f "$filepath" ]; then 
              echo "::warning::File $filepath from API response not found in checkout. Skipping."
              continue
            fi
            ORIGINAL_CONTENT_FOR_COMPARE=$(cat "$filepath")
            if [ "$ORIGINAL_CONTENT_FOR_COMPARE" = "$fixedcontent" ]; then
              echo "No actual change for $filepath. Skipping add."
              continue
            fi

            echo "Applying fix to $filepath"
            echo "$fixedcontent" > "$filepath"
            git add "$filepath"
            CHANGES_APPLIED=true
          done
          
          if [ "$CHANGES_APPLIED" = "true" ]; then
            if ! git diff --staged --quiet; then
              git config user.name "OET Bot" 
              git config user.email "bot@online-everything-tool.com" 
              git commit -m "chore: AI-assisted lint fixes"
              git push origin HEAD:${{ github.event.workflow_run.head_branch }} # Use head_branch from workflow_run
              echo "::notice::AI lint fixes committed and pushed. Workflow on PR branch will re-run."
            else
              echo "::notice::AI proposed no effective changes to be staged."
            fi
          else
            echo "::notice::AI returned no fixable content or all fixes resulted in null or no changes."
          fi