name: Build online-everything-tool and notify EC2 of Code Update

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          echo "Building online-everything-tool"
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Send SQS Message
        run: |
          aws sqs send-message \
            --queue-url ${{ secrets.AWS_SQS_URL }} \
            --message-body "{\"event\":\"code_update\",\"repository\":\"${{ github.repository }}\",\"commit\":\"${{ github.sha }}\",\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" \
        env:
          AWS_DEFAULT_REGION: us-east-1
