# .github/workflows/test_receiver_workflow.yml
name: Test Receiver Workflow (PAT Push Test)

on:
  workflow_run:
    workflows: ['Test Trigger Workflow (for PAT Push Test)'] # Match the name above
    types: [completed]

jobs:
  checkout_commit_push_with_pat:
    name: Checkout, Commit, and Push with PAT
    # Only run if the triggering workflow was successful and for a PR on a non-default branch
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0] != null &&
      github.event.workflow_run.pull_requests[0].head.ref != github.event.repository.default_branch
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for checkout with token and for push

    steps:
      - name: Log Triggering Workflow Info
        run: |
          echo "--- Triggering Workflow ('Test Trigger Workflow') Info ---"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head Branch from event: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA from event: ${{ github.event.workflow_run.head_sha }}"
          echo "Pull Request Number from event: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Pull Request Head Ref from event: ${{ github.event.workflow_run.pull_requests[0].head.ref }}"
          echo "Pull Request Head SHA from event: ${{ github.event.workflow_run.pull_requests[0].head.sha }}"
          echo "---------------------------------------------------------"

      - name: Checkout PR Code using PAT
        uses: actions/checkout@v4
        with:
          # Use the head SHA and ref from the pull_requests array in the workflow_run event,
          # as this is more reliable for PR context than workflow_run.head_sha/head_branch.
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }} 
          fetch-depth: 0 # To be able to push back

      - name: Make a dummy change and commit
        env:
          GH_TOKEN: ${{ secrets.AI_LINT_FIXER_PAT }} # For github-push-action
          PR_BRANCH_NAME: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
        run: |
          echo "Making a dummy change to README.md"
          # Create or append to README.md to ensure there's a change
          echo "Test commit by Test Receiver Workflow at $(date)" >> README.md
          
          git config --global user.name "Test Bot (PAT Push)"
          git config --global user.email "test-bot@example.com" # Or your bot's email
          
          git add README.md
          git commit -m "chore: Dummy commit by Test Receiver Workflow"
          
          echo "Changes committed locally."

      - name: Push changes using PAT
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: ${{ github.event.workflow_run.pull_requests[0].head.ref }} # Push to the PR's head branch
          github_token: ${{ secrets.AI_LINT_FIXER_PAT }} # Use the PAT for pushing
          force: false # Never force push from CI

      - name: Log Push Action
        run: |
          echo "Pushed dummy commit to branch ${{ github.event.workflow_run.pull_requests[0].head.ref }} using PAT."
          echo "Check if 'Test Trigger Workflow (for PAT Push Test)' runs again due to 'pull_request:synchronize'."