# .github/workflows/test_trigger_workflow.yml
name: Test Trigger Workflow (for PAT Push Test)

on:
  pull_request:
    types: [opened, synchronize]
    # No 'branches: - main' here, we'll filter by head_ref in the job 'if'
    # to ensure it's specifically for PRs *from* 'test-' branches.

jobs:
  main_job:
    name: Main Job for Test Trigger
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'test-')
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      head_branch: ${{ github.event.pull_request.head.ref }}
      
    steps:
      - name: Log PR Info
        run: |
          echo "Test Trigger Workflow running for PR #${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Head Ref (Branch): ${{ github.head_ref }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR Base Ref: ${{ github.base_ref }}"

      - name: Simulate Work and Conclude
        run: |
          echo "Simulating some work in Test Trigger Workflow..."
          sleep 5
          echo "Test Trigger Workflow completed."